//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanosPRO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecursosHumanosEntities2 : DbContext
    {
        public RecursosHumanosEntities2()
            : base("name=RecursosHumanosEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aguinaldo> Aguinaldo { get; set; }
        public virtual DbSet<Contratos> Contratos { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<HorasExtras> HorasExtras { get; set; }
        public virtual DbSet<Puestos> Puestos { get; set; }
        public virtual DbSet<Rendimiento> Rendimiento { get; set; }
        public virtual DbSet<Usaurios> Usaurios { get; set; }
        public virtual DbSet<Vacaciones> Vacaciones { get; set; }
        public virtual DbSet<Vacantes> Vacantes { get; set; }
    }
}
