//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanosPRO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacaciones
    {
        public int IdVacaciones { get; set; }
        public System.DateTime desde { get; set; }
        public System.DateTime hasta { get; set; }
        public int IdContrato { get; set; }
    
        public virtual Contratos Contratos { get; set; }
    }
}
